Update

diff --git a/watchdog b/watchdog
--- a/watchdog
+++ b/watchdog
@@ -13,13 +13,14 @@ function process_checker {
     do
         if test $(expr $(date +%s) -  $timestamp) -ge $(get_config $1 "watchtime");
         then
-            ps -e | grep $(get_config $1 "Name") >/dev/null || (sudo $(get_config $1 "binary") $(get_config $1 "arguments") >/dev/null 2>/dev/null && logger -s "[WatchDog] Starting of $(get_config $i 'Name')..." 2>>/var/log/watchdog);
+            logger -s "Check" 2>>/var/log/watchdog;
+            ps -e | grep $(get_config $1 "Name") >/dev/null || (sudo $(get_config $1 "binary") $(get_config $1 "arguments") >/dev/null 2>/dev/null && logger -s "[WatchDog] Starting of $(get_config $i 'Name')..." 2>>/var/log/watchdog;
+            timestamp=$(date +%s);
         fi;
-        timestamp=$(date +%s);
     done;
     if [[ ! $(get_config $1 "watchtime") || $(get_config $1 "watchtime") = "" || $(get_config $1 "watchtime") = 0 || $(get_config $1 "watchtime") -eq 0 ]];
     then
-        logger -s "[WatchDog] Error on $(get_config $i 'Name') services" 2>>/var/log/watchdog;
+        logger -s "[WatchDog] Error of configuration on $(get_config $i 'Name') services" 2>>/var/log/watchdog;
     fi;
 }
 
