Fix i 1

diff --git a/watchdog b/watchdog
--- a/watchdog
+++ b/watchdog
@@ -10,12 +10,12 @@ function get_config {
 function process_checker {
     timestamp=0;
     nb_try=0;
-    while [[ $(get_config $i 'enable') == "true" && $(get_config $1 "watchtime") -gt 0 ]];
+    while [[ $(get_config $1 'enable') == "true" && $(get_config $1 "watchtime") -gt 0 ]];
     do
         if test $(expr $(date +%s) -  $timestamp) -ge $(get_config $1 "watchtime");
         then
             logger -t watchdog "Checking process $(get_config $1 "Name")";
-            on_error=$(ps -e | grep $(get_config $1 "Name") >/dev/null && echo 0 || (sudo $(get_config $1 "binary") $(get_config $1 "arguments") >/dev/null 2>/dev/null && logger -t watchdog "Starting of $(get_config $i 'Name')..." && echo 1));
+            on_error=$(ps -e | grep $(get_config $1 "Name") >/dev/null && echo 0 || (sudo $(get_config $1 "binary") $(get_config $1 "arguments") >/dev/null 2>/dev/null && logger -t watchdog "Starting of $(get_config $1 'Name')..." && echo 1));
             if [ "$on_error" == "1" ];
             then
                 nb_try=$(expr $nb_try + 1);
@@ -31,7 +31,7 @@ function process_checker {
     done;
     if [[ ! $(get_config $1 "watchtime") || $(get_config $1 "watchtime") = "" || $(get_config $1 "watchtime") = 0 || $(get_config $1 "watchtime") -eq 0 ]];
     then
-        logger -t "Error of configuration on $(get_config $i 'Name') services";
+        logger -t "Error of configuration on $(get_config $1 'Name') services";
     fi;
 }
 
